version: '3'

services:
  poll:
    restart: always
    build: ./poll
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    networks:
      - poll-tier
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  db:
    restart: always
    image: postgres:16
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    networks:
      - result-tier
      - back-tier

  worker:
    restart: always
    build: ./worker
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
      - POSTGRES_PORT=5432
    networks:
      - back-tier
    depends_on:
      - redis
      - db

  result:
    restart: always
    build: ./result
    ports:
      - "5001:80"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    networks:
      - result-tier
    depends_on:
      - db

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: