#!/usr/bin/python3

from math import *
import sys

def my_pong(x0, y0, z0, x1, y1, z1, n):
    x2 = (x1-x0)
    y2 = (y1-y0)
    z2 = (z1-z0)

    print("The velocity vector of the ball is:")
    print("({:.2f}, {:.2f}, {:.2f})".format(float(x2),float(y2),float(z2),))
    print("At time t + {}, ball coordinates will be:".format(int(n)))
    print("({:.2f}, {:.2f}, {:.2f})".format(float((x1 + (n*x2))), float((y1 + (n*y2))), float((z1 + (n*z2)))))
    if((z1 > z0 and z1 > 0) or (z1 < z0 and z1 < 0) or (z1 == z0 and (z1 != 0 or z2 != 0))):
        print("The ball won't reach the paddle.")
        sys.exit(0)
    else:
        print("The incidence angle is:")
        if (z1 == 0 and z2 == 0):
            print("0.00 degrees")
            sys.exit(0)
        result = degrees(asin(z2/(sqrt((x2**2 + y2**2 + z2**2)))))
    if (result < 0):
        result *= -1
    print("{:.2f} degrees".format(result))

try:
    argv = [float(i) for i in sys.argv[1:]]
    x0, y0, z0, x1, y1, z1, n = argv
    if (n % 1 != 0 or n < 0):
        sys.exit(84)
    n = int(n)
    my_pong(x0, y0, z0, x1, y1, z1, n)
except ValueError:
    sys.exit(84)
if (len(sys.argv) != 8):
    sys.exit(84)
