##
## EPITECH PROJECT, 2023
## Makefile
## File description:
## 105demography
##

NAME=	105demography

OBJ	=	105demography.py

all:	$(NAME)

$(NAME):	$(OBJ)
		cp $(OBJ) $(NAME)
		chmod +x $(NAME)

clean:
	$(RM) *~
	$(RM) $(NAME)

fclean:	clean
	$(RM) $(NAME)

re:	fclean all