name: Action

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: 'git@github.com:EpitechPromo2028/B-MUL-200-MPL-2-1-myrpg-vincent.bichat.git'
  EXECUTABLES: 'my_rpg'

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    if: github.repository == 'VALKYRIA-RPG/GAME-RPG'
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@main
      - name: Generate .log file
        run: check.sh $(pwd) $(pwd)
      - name: Check for coding style errors in .log file
        run: |
          if [ -s coding-style-reports.log ]; then
            while IFS= read -r line
            do
              FILE=$(echo $line | cut -d':' -f1)
              LINE=$(echo $line | cut -d':' -f2)
              MSG=$(echo $line | cut -d':' -f3-)
              echo "::error file=$FILE,line=$LINE::$MSG"
             done < coding-style-reports.log
             exit 1
            fi
          rm -f coding-style-reports.log
  check_program_compilation:
    runs-on: ubuntu-latest
    needs: check_coding_style
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Check program compilation
        run: make
        timeout-minutes: 2
      - name: Clean up
        run: make clean
      - name: Check executables
        run: |
          for file in $EXECUTABLES; do
            if [ ! -x "$file" ]; then
              echo "$file is not executable or does not exist"
              exit 1
            fi
          done
  push_to_mirror:
    runs-on: ubuntu-latest
    needs: check_program_compilation
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@main
        with:
          ssh_private_key: ${{ secrets.MIRRORING_RPG }}
          target_repo_url: ${{ env.MIRROR_URL }}